apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-server
  namespace: mail-server
  labels:
    app: redis-server
spec:
  serviceName: "redis-service"
  replicas: 3
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
        name: redis-server
    spec:
      containers:
        - name: redis-server
          image: redis:alpine
          args: ["--appendonly", "yes"]
          ports:
            - name: redis-port
              containerPort: 6379
          envFrom:
            - secretRef:
                name: redis-secret
          volumeMounts:
            - name: lv-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: lv-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
