apiVersion: v1
kind: Service

metadata:
  name: server-svc
  namespace: mail-server

spec:
  type: LoadBalancer
  selector:
    app: mail-server
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
