apiVersion: v1
kind: Secret

metadata:
  name: mail-server-secret
  namespace: mail-server

type: Opaque

stringData:
  MONGODB_URI: mongodb://root:examplepassword@mongodb-loadbalancer-svc:27017/?authSource=admin
