apiVersion: v1
kind: Secret

metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: mail-server

stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: examplepassword
